# kubectl get configmap aws-auth -n kube-system -o yaml
# aws sts get-caller-identity check which user
# after login to suresh and add credentials
# install kubectl and conncet kubectl to an eks cluster by creating a kubeconfig file 
apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::084134273236:role/eksctl-roboshop-nodegroup-roboshop-NodeInstanceRole-UTIgUG94gd61
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::084134273236:user/suresh
      username: suresh
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-19T15:44:18Z"
  name: aws-auth
  namespace: kube-system
  uid: 19b72720-656c-4ebf-a90d-7f605072ae2a



#if u need api version "kubectl api-resources | grep persistent"

## service account

# It is a non human user that uses to run. by default when we create namespace service account with name is default created


# whenever namespace created by default service account also created..
# kubectl get sa -n roboshop
# kubectl describe sa default -n roboshop
# kubectl describe pod <name> -n roboshop
# kubectl get sa 
---

# 1. create oidc provider
# 2. create policy and attach permissions
# 3. create iamserviceacccount
# 4. role and RoleBinding 
# 4.1 in role binding replace the api group with namespace 
# 5. aws cli to get secret value check in main admin server
# 6. if we want to check in pod  it was running or not just install the aws cli or ru the image

# Now i have to practice ingress,rbac,service account 

# 69-session





